name: Main Gate

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # we build with net462 TFM
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Build
      run: dotnet build Checker.MSBuild
    - name: Test Net 48
      run: dotnet test Checker.Tests.net48
    - name: Test Net 60
      run: dotnet test Checker.Tests.net60
